# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2022
#  @credits:    AKAE
#
#  @license:    GPLv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       unittest.yml
#  @date:       2022-08-10
#
#  @brief:      runs unit test
#
# ************************************************************************


name: Unittest

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: OS Version
        run: |
          cat /etc/os-release
      - name: texrefchk
        run: |
          # 01_pass
          ret=$(./texrefchk.sh --texdir=./test/01_pass)
          if [ 0 -eq $? ]; then echo "[ PASS ]   test: 01_pass"; else [ FAIL ]   test: 01_pass; echo $ret; exit 1; fi;
          # 02_fail
          ret=$(./texrefchk.sh --texdir=./test/02_fail)
          exit 0
          #if [ 1 -eq $? ]; then echo "[ PASS ]   test: 02_fail"; else [ FAIL ]   test: 02_fail; echo $ret; exit 1; fi;
          #exit 1
